from typing import Dict, TypedDict
from BaseClasses import Item, ItemClassification

class SS2item(Item):
    game = "System Shock 2"

class ItemDict(TypedDict):
    id: int
    classification: ItemClassification
    count: int
    option: str


SS2items: Dict[str, ItemDict] = {
"Wrench": {"id": 1,
    "classification": "filler",
    "count": 14,
    "option": ""},
"Nikki's Room Access Card": {"id": 3,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Candy's Room Access Card": {"id": 4,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Sven's Room Access Card": {"id": 5,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Lance's Room Access Card": {"id": 6,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Sympathetic Resonator": {"id": 7,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Starting Wrench": {"id": 8,
    "classification": "filler",
    "count": 1,
    "option": "StartingWrench"},
"Pistol": {"id": 9,
    "classification": "progression",
    "count": 5,
    "option": ""},
"Damaged Shotgun": {"id": 10,
    "classification": "progression",
    "count": 8,
    "option": ""},
"Broken Pistol": {"id": 11,
    "classification": "progression",
    "count": 10,
    "option": ""},
"Damaged Pistol": {"id": 12,
    "classification": "progression",
    "count": 18,
    "option": ""},
"Black-Ops Psionic Amplifier": {"id": 13,
    "classification": "progression",
    "count": 7,
    "option": ""},
"Anti-radiation Hypo": {"id": 14,
    "classification": "progression",
    "count": 30,
    "option": ""},
"MFD Game Player": {"id": 15,
    "classification": "filler",
    "count": 4,
    "option": ""},
"Game Cartridge: Swinekeeper": {"id": 16,
    "classification": "filler",
    "count": 2,
    "option": ""},
"10 Nanites": {"id": 17,
    "classification": "filler",
    "count": 15,
    "option": ""},
"Hybrid Organ": {"id": 18,
    "classification": "useful",
    "count": 1,
    "option": ""},
"Small Standard Clip": {"id": 19,
    "classification": "useful",
    "count": 38,
    "option": ""},
"Speed Booster": {"id": 20,
    "classification": "useful",
    "count": 17,
    "option": ""},
"Standard Clip": {"id": 21,
    "classification": "useful",
    "count": 16,
    "option": ""},
"Small AP Clip": {"id": 22,
    "classification": "useful",
    "count": 23,
    "option": ""},
"DIEGO Re: Yanking my chain Audio Log": {"id": 23,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Anti-Personnel Shotgun Shells": {"id": 24,
    "classification": "useful",
    "count": 24,
    "option": ""},
"Medical Hypo": {"id": 25,
    "classification": "useful",
    "count": 44,
    "option": ""},
"20 Nanites": {"id": 26,
    "classification": "filler",
    "count": 63,
    "option": ""},
"CURTIS Re: Coolant leaks Audio Log": {"id": 27,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Psi Hypo": {"id": 28,
    "classification": "progression",
    "count": 50,
    "option": ""},
"GRASSI Re: All work, no play Audio Log": {"id": 29,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Version 1 Research Software Module": {"id": 30,
    "classification": "filler",
    "count": 4,
    "option": ""},
"DELACROIX Re: Xerces Audio Log": {"id": 31,
    "classification": "filler",
    "count": 1,
    "option": ""},
"GRASSI Re: Implant job Audio Log": {"id": 32,
    "classification": "filler",
    "count": 1,
    "option": ""},
"6 Rifled Slugs": {"id": 33,
    "classification": "useful",
    "count": 29,
    "option": ""},
"4 Cyber Modules": {"id": 34,
    "classification": "progression",
    "count": 12,
    "option": ""},
"5 Nanites": {"id": 35,
    "classification": "filler",
    "count": 3,
    "option": ""},
"BrawnBoost": {"id": 36,
    "classification": "useful",
    "count": 4,
    "option": ""},
"2 Cyber Modules": {"id": 37,
    "classification": "progression",
    "count": 22,
    "option": ""},
"GRASSI Re: Animal Rights? Audio Log": {"id": 38,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Anti-toxin hypo": {"id": 39,
    "classification": "useful",
    "count": 34,
    "option": ""},
"WATTS Re: Watson autopsy Audio Log": {"id": 40,
    "classification": "filler",
    "count": 1,
    "option": ""},
"WATTS Re: Maintenance conduit Audio Log": {"id": 41,
    "classification": "progression",
    "count": 1,
    "option": ""},
"DELACROIX Re: Not ready Audio Log": {"id": 42,
    "classification": "filler",
    "count": 1,
    "option": ""},
"CURTIZ Re: More trouble": {"id": 43,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Strength Booster": {"id": 44,
    "classification": "useful",
    "count": 2,
    "option": ""},
"Deck 2 Chemical Storage Manifest": {"id": 45,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Fermium": {"id": 46,
    "classification": "useful",
    "count": 6,
    "option": ""},
"Vanadium": {"id": 47,
    "classification": "progression",
    "count": 6,
    "option": ""},
"Gallium": {"id": 48,
    "classification": "useful",
    "count": 5,
    "option": ""},
"Antimony": {"id": 49,
    "classification": "progression",
    "count": 11,
    "option": ""},
"Yttrium": {"id": 50,
    "classification": "progression",
    "count": 10,
    "option": ""},
"Copper": {"id": 51,
    "classification": "useful",
    "count": 7,
    "option": ""},
"Californium": {"id": 52,
    "classification": "filler",
    "count": 6,
    "option": ""},
"Sodium": {"id": 53,
    "classification": "useful",
    "count": 5,
    "option": ""},
"Osmium": {"id": 54,
    "classification": "useful",
    "count": 4,
    "option": ""},
"Iridium": {"id": 55,
    "classification": "useful",
    "count": 12,
    "option": ""},
"Arsenic": {"id": 56,
    "classification": "filler",
    "count": 7,
    "option": ""},
"Cesium": {"id": 57,
    "classification": "useful",
    "count": 13,
    "option": ""},
"Hassium": {"id": 58,
    "classification": "useful",
    "count": 10,
    "option": ""},
"Tellurium": {"id": 59,
    "classification": "progression",
    "count": 15,
    "option": ""},
"Molybdenum": {"id": 60,
    "classification": "progression",
    "count": 9,
    "option": ""},
"Technetium": {"id": 61,
    "classification": "progression",
    "count": 12,
    "option": ""},
"Radium": {"id": 62,
    "classification": "useful",
    "count": 10,
    "option": ""},
"Barium": {"id": 63,
    "classification": "useful",
    "count": 13,
    "option": ""},
"Selenium": {"id": 64,
    "classification": "progression",
    "count": 7,
    "option": ""},
"Dead Power Cell": {"id": 65,
    "classification": "progression",
    "count": 2,
    "option": ""},
"Science Access Card": {"id": 66,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Broken Grenade Launcher": {"id": 67,
    "classification": "progression",
    "count": 3,
    "option": ""},
"Damaged Assault Rifle": {"id": 68,
    "classification": "progression",
    "count": 2,
    "option": ""},
"Damaged Stasis Field Generator": {"id": 69,
    "classification": "progression",
    "count": 1,
    "option": ""},
"EMP Rifle": {"id": 70,
    "classification": "progression",
    "count": 4,
    "option": ""},
"KORENCHKIN Re: First contact Audio Log": {"id": 71,
    "classification": "filler",
    "count": 1,
    "option": ""},
"TURNBULL Re: Procedures Audio Log": {"id": 72,
    "classification": "filler",
    "count": 1,
    "option": ""},
"POLITO Re: Strange AI Audio Log": {"id": 73,
    "classification": "filler",
    "count": 1,
    "option": ""},
"SUAREZ Re: 100% Torture Audio Log": {"id": 74,
    "classification": "filler",
    "count": 1,
    "option": ""},
"3 Proximity Grenades": {"id": 75,
    "classification": "useful",
    "count": 10,
    "option": ""},
"Auto-Diagnostic Medical Kit": {"id": 76,
    "classification": "useful",
    "count": 30,
    "option": ""},
"Suit of Light Combat Armor": {"id": 77,
    "classification": "useful",
    "count": 5,
    "option": ""},
"3 Fragmentation Grenades": {"id": 78,
    "classification": "useful",
    "count": 14,
    "option": ""},
"Portable Battery": {"id": 79,
    "classification": "useful",
    "count": 6,
    "option": ""},
"Box of 12 Anti-Personnel Bullets": {"id": 80,
    "classification": "useful",
    "count": 18,
    "option": ""},
"Suit of Standard-Issue Combat Armor": {"id": 81,
    "classification": "useful",
    "count": 4,
    "option": ""},
"R & D Access Card": {"id": 82,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Surgical Unit Activation Key": {"id": 83,
    "classification": "useful",
    "count": 7,
    "option": ""},
"WATTS Re: Nonsense Audio Log": {"id": 84,
    "classification": "filler",
    "count": 1,
    "option": ""},
"CURTIZ Re: Lifts are out Audio Log": {"id": 85,
    "classification": "filler",
    "count": 1,
    "option": ""},
"CURTIZ Re: Rad Hypos Audio Log": {"id": 86,
    "classification": "filler",
    "count": 1,
    "option": ""},
"WATTS Re: Patient Watson Audio Log": {"id": 87,
    "classification": "filler",
    "count": 1,
    "option": ""},
"GRASSI Re: Damn chimps Audio Log": {"id": 88,
    "classification": "filler",
    "count": 1,
    "option": ""},
"WATTS Re: Patient Watson, pt. 2 Audio Log": {"id": 89,
    "classification": "filler",
    "count": 1,
    "option": ""},
"30 Nanites": {"id": 90,
    "classification": "filler",
    "count": 14,
    "option": ""},
"Deck 2 crew Access Card": {"id": 91,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Small Beaker": {"id": 92,
    "classification": "useful",
    "count": 17,
    "option": ""},
"Broken Assault Rifle": {"id": 93,
    "classification": "progression",
    "count": 2,
    "option": ""},
"Laser Rapier": {"id": 94,
    "classification": "progression",
    "count": 5,
    "option": ""},
"Psi Booster": {"id": 95,
    "classification": "useful",
    "count": 11,
    "option": ""},
"Broken Shotgun": {"id": 96,
    "classification": "progression",
    "count": 6,
    "option": ""},
"MARTIN Re: Ambush Audio Log": {"id": 97,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DELACROIX Re: A new friend? Audio Log": {"id": 98,
    "classification": "filler",
    "count": 1,
    "option": ""},
"CURTIZ Re: Just us Audio Log": {"id": 99,
    "classification": "filler",
    "count": 1,
    "option": ""},
"SANGER Re: Delacroix Audio Log": {"id": 100,
    "classification": "filler",
    "count": 1,
    "option": ""},
"PsiBoost(TM) Implant": {"id": 101,
    "classification": "useful",
    "count": 2,
    "option": ""},
"Box of 6 Anti-personnel Bullets": {"id": 102,
    "classification": "useful",
    "count": 18,
    "option": ""},
"Deck 1 Chemical Storage Manifest": {"id": 103,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Version 1 Repair Software Module": {"id": 104,
    "classification": "useful",
    "count": 3,
    "option": ""},
"SANGER Re: The soldiers Audio Log": {"id": 105,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DELACROIX Re: Tau Ceti 5": {"id": 106,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Hazard Suit": {"id": 107,
    "classification": "useful",
    "count": 4,
    "option": ""},
"DELACROIX Re: Taking action Audio Log": {"id": 108,
    "classification": "filler",
    "count": 1,
    "option": ""},
"AP Clip": {"id": 109,
    "classification": "useful",
    "count": 15,
    "option": ""},
"CURTIZ Re: That leak again Audio Log": {"id": 110,
    "classification": "filler",
    "count": 1,
    "option": ""},
"SANGER Re: Locking Eng. Control": {"id": 111,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DELACROIX Re: Fluidics backdoor Audio Log": {"id": 112,
    "classification": "progression",
    "count": 1,
    "option": ""},
"MARTIN Re: Cargo bay 2 Audio Log": {"id": 113,
    "classification": "filler",
    "count": 1,
    "option": ""},
"BRONSON Re: Turret problems Audio Log": {"id": 114,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Annelid Healing Gland": {"id": 115,
    "classification": "useful",
    "count": 2,
    "option": ""},
"Security Access Card": {"id": 116,
    "classification": "progression",
    "count": 2,
    "option": ""},
"45m/dEx circuit board": {"id": 117,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Broken Laser Pistol": {"id": 118,
    "classification": "progression",
    "count": 1,
    "option": ""},
"French-Epstein Device": {"id": 119,
    "classification": "useful",
    "count": 14,
    "option": ""},
"SANGER Re: Locked in Audio Log": {"id": 120,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Cargo Bay 2A/2B Access Card": {"id": 121,
    "classification": "progression",
    "count": 1,
    "option": ""},
"SIDDONS Re: Lame old me Audio Log": {"id": 122,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Game Cartridge: OverWorld Zero": {"id": 123,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DIEGO Re: Resist the call Audio Log": {"id": 124,
    "classification": "filler",
    "count": 1,
    "option": ""},
"SUAREZ Re: Hang tight Audio Log": {"id": 125,
    "classification": "filler",
    "count": 1,
    "option": ""},
"3 Cyber Modules": {"id": 126,
    "classification": "progression",
    "count": 26,
    "option": ""},
"SwiftBoost(TM) Implant": {"id": 127,
    "classification": "useful",
    "count": 5,
    "option": ""},
"MALONE Re: Further experiments Audio Log": {"id": 128,
    "classification": "filler",
    "count": 1,
    "option": ""},
"MALONE Re: Psionic chimps! Audio Log": {"id": 129,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Version 1 Hacking Software Module": {"id": 130,
    "classification": "useful",
    "count": 2,
    "option": ""},
"BRONSON Re: Hacking Turrets Audio Log": {"id": 131,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DIEGO Re: Is it so bad? Audio Log": {"id": 132,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DELACROIX Re: Be Brave Audio Log": {"id": 133,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Grenade Launcher": {"id": 134,
    "classification": "progression",
    "count": 2,
    "option": ""},
"Laser Pistol": {"id": 135,
    "classification": "progression",
    "count": 4,
    "option": ""},
"3 EMP grenade rounds": {"id": 136,
    "classification": "useful",
    "count": 8,
    "option": ""},
"DELACROIX Re: A ray of hope Audio Log": {"id": 137,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DELACROIX Re: Killing the worms Audio Log": {"id": 138,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Game Cartridge: Swine Hunter": {"id": 139,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Toxin-A": {"id": 140,
    "classification": "progression",
    "count": 5,
    "option": ""},
"LabAssistant(TM) Implant": {"id": 141,
    "classification": "progression",
    "count": 2,
    "option": ""},
"KORENCHKIN Re: Miracles Audio Log": {"id": 142,
    "classification": "filler",
    "count": 1,
    "option": ""},
"MILLER Re: Our work here Audio Log": {"id": 143,
    "classification": "filler",
    "count": 1,
    "option": ""},
"40 Nanites": {"id": 144,
    "classification": "filler",
    "count": 10,
    "option": ""},
"MILLER Re: Wondrous toy Audio Log": {"id": 145,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Hydroponics B Access Card": {"id": 146,
    "classification": "useful",
    "count": 1,
    "option": ""},
"DELACROIX Re: Making a change Audio Log": {"id": 147,
    "classification": "filler",
    "count": 1,
    "option": ""},
"KORENCHKIN Re: A new purpose Audio Log": {"id": 148,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Hydroponics A Access Card": {"id": 149,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Auto-Repair Unit": {"id": 150,
    "classification": "progression",
    "count": 8,
    "option": ""},
"MILLER Re: The children Audio Log": {"id": 151,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Maintenance Tool": {"id": 152,
    "classification": "useful",
    "count": 43,
    "option": ""},
"LOESSER Re: Where are they? Audio Log": {"id": 153,
    "classification": "filler",
    "count": 1,
    "option": ""},
"MILLER Re: Nurse bloome Audio Log": {"id": 154,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Version 1 Modification Software Module": {"id": 155,
    "classification": "useful",
    "count": 2,
    "option": ""},
"BLOOME Re: Worried Audio Log": {"id": 156,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Deck 3 Chemical Storage Manifest": {"id": 157,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Assault Rifle": {"id": 158,
    "classification": "progression",
    "count": 2,
    "option": ""},
"POLITO Re: AI voice fragment Audio Log": {"id": 159,
    "classification": "filler",
    "count": 1,
    "option": ""},
"TURNBULL Re: Changing Audio Log": {"id": 160,
    "classification": "filler",
    "count": 1,
    "option": ""},
"3 Incendiary Grenade Rounds": {"id": 161,
    "classification": "useful",
    "count": 10,
    "option": ""},
"Version 2 Hacking Software Module": {"id": 162,
    "classification": "useful",
    "count": 1,
    "option": ""},
"Hydroponics D Access Card": {"id": 163,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Broken EMP Rifle": {"id": 164,
    "classification": "progression",
    "count": 2,
    "option": ""},
"Version 2 Repair Software Module": {"id": 165,
    "classification": "useful",
    "count": 3,
    "option": ""},
"Large Beaker": {"id": 166,
    "classification": "useful",
    "count": 14,
    "option": ""},
"LOESSER Re: Miller Audio Log": {"id": 167,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DIEGO Re: Our alliance Audio Log": {"id": 168,
    "classification": "filler",
    "count": 1,
    "option": ""},
"EndurBoost(TM) Implant": {"id": 169,
    "classification": "useful",
    "count": 3,
    "option": ""},
"KORENCHKIN Re: Glory Audio Log": {"id": 170,
    "classification": "filler",
    "count": 1,
    "option": ""},
"65 nanites": {"id": 171,
    "classification": "filler",
    "count": 5,
    "option": ""},
"Suit of Powered Armor": {"id": 172,
    "classification": "useful",
    "count": 2,
    "option": ""},
"YOUNT Re: Sim Units Audio Log": {"id": 173,
    "classification": "filler",
    "count": 1,
    "option": ""},
"MALICK Re: My red friends Audio Log": {"id": 174,
    "classification": "filler",
    "count": 1,
    "option": ""},
"SIDDONS Re: Civil war Audio Log": {"id": 175,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Version 2 Modification Software Module": {"id": 176,
    "classification": "useful",
    "count": 4,
    "option": ""},
"SUAREZ Re: Let's do it Audio Log": {"id": 177,
    "classification": "filler",
    "count": 1,
    "option": ""},
"15 nanites": {"id": 178,
    "classification": "filler",
    "count": 13,
    "option": ""},
"KORENCHKIN Re: Everything old... Audio Log": {"id": 179,
    "classification": "filler",
    "count": 1,
    "option": ""},
"MALICK Re: Good bye Audio Log": {"id": 180,
    "classification": "filler",
    "count": 1,
    "option": ""},
"SIDDONS Re: Bad feeling... Audio Log": {"id": 181,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Deck 4 Chemical Storage Manifest": {"id": 182,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Crystal Shard": {"id": 183,
    "classification": "progression",
    "count": 17,
    "option": ""},
"Damaged EMP Rifle": {"id": 184,
    "classification": "progression",
    "count": 2,
    "option": ""},
"WormMind Implant": {"id": 185,
    "classification": "useful",
    "count": 4,
    "option": ""},
"Shotgun": {"id": 186,
    "classification": "progression",
    "count": 2,
    "option": ""},
"Damaged Laser Pistol": {"id": 187,
    "classification": "progression",
    "count": 2,
    "option": ""},
"BAYLISS Re: What gives? Audio Log": {"id": 188,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Arachnid Organ": {"id": 189,
    "classification": "useful",
    "count": 1,
    "option": ""},
"WOOD Re: Crystal gifts Audio Log": {"id": 190,
    "classification": "filler",
    "count": 1,
    "option": ""},
"MALICK Re: Bronson Audio Log": {"id": 191,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Game Cartridge: Street Hog": {"id": 192,
    "classification": "filler",
    "count": 1,
    "option": ""},
"BRONSON Re: Sabotage Audio Log": {"id": 193,
    "classification": "filler",
    "count": 1,
    "option": ""},
"BRONSON Re: No shirkers Audio Log": {"id": 194,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Interpolated Simulation Chip": {"id": 195,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Quantum Simulation Chip": {"id": 196,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Broken Stasis Field Generator": {"id": 197,
    "classification": "progression",
    "count": 2,
    "option": ""},
"Broken Fusion Cannon": {"id": 198,
    "classification": "progression",
    "count": 1,
    "option": ""},
"ExperTech(TM) Implant": {"id": 199,
    "classification": "useful",
    "count": 2,
    "option": ""},
"MALICK Re: Sim Unit 3 Audio Log": {"id": 200,
    "classification": "filler",
    "count": 1,
    "option": ""},
"SUAREZ Re: Don't stop Audio Log": {"id": 201,
    "classification": "filler",
    "count": 1,
    "option": ""},
"BRONSON Re: Martial law Audio Log": {"id": 202,
    "classification": "filler",
    "count": 1,
    "option": ""},
"20 Prisms": {"id": 203,
    "classification": "useful",
    "count": 10,
    "option": ""},
"WormBlood Implant": {"id": 204,
    "classification": "useful",
    "count": 2,
    "option": ""},
"BRONSON Re: Resist Audio Log": {"id": 205,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DIEGO Re: Cease and desist Audio Log": {"id": 206,
    "classification": "filler",
    "count": 1,
    "option": ""},
"BRONSON Re: MedSci sub-armory Audio Log": {"id": 207,
    "classification": "progression",
    "count": 1,
    "option": ""},
"DELACROIX Re: The main elevator Audio Log": {"id": 208,
    "classification": "filler",
    "count": 1,
    "option": ""},
"35 Nanites": {"id": 209,
    "classification": "filler",
    "count": 6,
    "option": ""},
"Linear Simulation Chip": {"id": 210,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Damaged Fusion Cannon": {"id": 211,
    "classification": "progression",
    "count": 3,
    "option": ""},
"Suit of Worm Skin Armor": {"id": 212,
    "classification": "useful",
    "count": 5,
    "option": ""},
"Viral Proliferator": {"id": 213,
    "classification": "progression",
    "count": 4,
    "option": ""},
"10 Cyber Modules": {"id": 214,
    "classification": "progression",
    "count": 19,
    "option": ""},
"Suit of Heavy Combat Armor": {"id": 215,
    "classification": "useful",
    "count": 5,
    "option": ""},
"50 Nanites": {"id": 216,
    "classification": "filler",
    "count": 19,
    "option": ""},
"MURDOCH Re: Ick Audio Log": {"id": 217,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Rumbler Organ": {"id": 218,
    "classification": "useful",
    "count": 1,
    "option": ""},
"Game Cartridge: Golf": {"id": 219,
    "classification": "filler",
    "count": 1,
    "option": ""},
"YANG Re: Blackouts Audio Log": {"id": 220,
    "classification": "filler",
    "count": 1,
    "option": ""},
"MURDOCH Re: What's going on? Audio Log": {"id": 221,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DELACROIX Re: Friends and enemies Audio Log": {"id": 222,
    "classification": "filler",
    "count": 1,
    "option": ""},
"YANG Re: Barricaded in Audio Log": {"id": 223,
    "classification": "filler",
    "count": 1,
    "option": ""},
"YANG Re: Victory! Audio Log": {"id": 224,
    "classification": "filler",
    "count": 1,
    "option": ""},
"CORTEZ Re: The mall Audio Log": {"id": 225,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DELACROIX Re: Turn on transmitter Audio Log": {"id": 226,
    "classification": "filler",
    "count": 1,
    "option": ""},
"CORTEZ Re: Transmitter units Audio Log": {"id": 227,
    "classification": "filler",
    "count": 1,
    "option": ""},
"3 Disruption Grenade Rounds": {"id": 228,
    "classification": "useful",
    "count": 20,
    "option": ""},
"Game Cartridge: Tic-Tac-Triop": {"id": 229,
    "classification": "filler",
    "count": 1,
    "option": ""},
"10 Prisms": {"id": 230,
    "classification": "useful",
    "count": 11,
    "option": ""},
"Athletics Access Card": {"id": 231,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Deck 5 Crew Access Card": {"id": 232,
    "classification": "progression",
    "count": 1,
    "option": ""},
"CORTEZ Re: Worm artifact Audio Log": {"id": 233,
    "classification": "filler",
    "count": 1,
    "option": ""},
"SUAREZ Re: Where are you? Audio Log": {"id": 234,
    "classification": "filler",
    "count": 1,
    "option": ""},
"55 nanites": {"id": 235,
    "classification": "filler",
    "count": 5,
    "option": ""},
"SIDDONS Re: Escape pods Audio Log": {"id": 236,
    "classification": "filler",
    "count": 1,
    "option": ""},
"6 Cyber Modules": {"id": 237,
    "classification": "progression",
    "count": 10,
    "option": ""},
"8 Cyber Modules": {"id": 238,
    "classification": "progression",
    "count": 5,
    "option": ""},
"CORTEZ Re: Under the garden Audio Log": {"id": 239,
    "classification": "progression",
    "count": 1,
    "option": ""},
"DELACROIX Re: Trusting SHODAN Audio Log": {"id": 240,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Version 2 Research Software Module": {"id": 241,
    "classification": "filler",
    "count": 1,
    "option": ""},
"5 Cyber Modules": {"id": 242,
    "classification": "progression",
    "count": 9,
    "option": ""},
"MURDOCH Re: ------- Audio Log": {"id": 243,
    "classification": "filler",
    "count": 1,
    "option": ""},
"36 Worm Clusters": {"id": 244,
    "classification": "useful",
    "count": 1,
    "option": ""},
"Version 3 Hacking Software Module": {"id": 245,
    "classification": "useful",
    "count": 3,
    "option": ""},
"Deck 5 Chemical Storage Manifest": {"id": 246,
    "classification": "filler",
    "count": 1,
    "option": ""},
"KORENCHKIN Re: Coming home Audio Log": {"id": 247,
    "classification": "filler",
    "count": 1,
    "option": ""},
"503 Nanites": {"id": 248,
    "classification": "useful",
    "count": 1,
    "option": ""},
"1 Nanite": {"id": 249,
    "classification": "filler",
    "count": 1,
    "option": ""},
"ROSENBERG Re: Looking out for #1 Audio Log": {"id": 250,
    "classification": "progression",
    "count": 1,
    "option": ""},
"SIDDONS Re: Find me Audio Log": {"id": 251,
    "classification": "filler",
    "count": 1,
    "option": ""},
"ROSENBERG Re: My nanites Audio Log": {"id": 252,
    "classification": "filler",
    "count": 1,
    "option": ""},
"ROSENBERG Re: Defending the reps Audio Log": {"id": 253,
    "classification": "filler",
    "count": 1,
    "option": ""},
"7 Cyber Modules": {"id": 254,
    "classification": "progression",
    "count": 2,
    "option": ""},
"MCKAY Re: They're escaping! Audio Log": {"id": 255,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Version 3 Research Software Module": {"id": 256,
    "classification": "filler",
    "count": 3,
    "option": ""},
"MCKAY Re: A monkey wrench Audio Log": {"id": 257,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DELACROIX Re: SH$8dD@#N'S pl4n Audio Log": {"id": 258,
    "classification": "filler",
    "count": 1,
    "option": ""},
"KORENCHKIN Re: My completion Audio Log": {"id": 259,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Version 3 Repair Software Module": {"id": 260,
    "classification": "useful",
    "count": 3,
    "option": ""},
"DELACROIX Re: SHODAN Audio Log": {"id": 261,
    "classification": "filler",
    "count": 1,
    "option": ""},
"NORRIS Re: Worms and guns Audio Log": {"id": 262,
    "classification": "filler",
    "count": 1,
    "option": ""},
"PREFONTAINE Re: Floating psi-users Audio Log": {"id": 263,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Bridge Access Card": {"id": 264,
    "classification": "progression",
    "count": 1,
    "option": ""},
"DIEGO Re: My responsibility Audio Log": {"id": 265,
    "classification": "filler",
    "count": 1,
    "option": ""},
"KORENCHKIN Re: The machine-mother": {"id": 266,
    "classification": "filler",
    "count": 1,
    "option": ""},
"SUAREZ Re: Pod problems Audio Log": {"id": 267,
    "classification": "filler",
    "count": 1,
    "option": ""},
"WormHeart Implant": {"id": 268,
    "classification": "useful",
    "count": 4,
    "option": ""},
"MYERS Re: Security rewired Audio Log": {"id": 269,
    "classification": "progression",
    "count": 1,
    "option": ""},
"NORRIS Re: Korenchkin Audio Log": {"id": 270,
    "classification": "filler",
    "count": 1,
    "option": ""},
"NORRIS Re: What's going on? Audio Log": {"id": 271,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Shuttle Bay Access Card": {"id": 272,
    "classification": "progression",
    "count": 1,
    "option": ""},
"NORRIS Re: Shuttle control Audio Log": {"id": 273,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Deck 6 Chemical Storage Manifest": {"id": 274,
    "classification": "filler",
    "count": 1,
    "option": ""},
"KORENCHKIN Re: The lovers Audio Log": {"id": 275,
    "classification": "filler",
    "count": 1,
    "option": ""},
"85 Nanites": {"id": 276,
    "classification": "filler",
    "count": 1,
    "option": ""},
"NORRIS Re: A dream Audio Log": {"id": 277,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Ops Override Access Card": {"id": 278,
    "classification": "progression",
    "count": 1,
    "option": ""},
"79 Nanites": {"id": 279,
    "classification": "filler",
    "count": 6,
    "option": ""},
"BAYLISS Re: Tau Ceti Audio Log": {"id": 280,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Rickenbacker Access Card": {"id": 281,
    "classification": "progression",
    "count": 1,
    "option": ""},
"BAYLISS Re: Tau Ceti, Pt. 3 Audio Log": {"id": 282,
    "classification": "filler",
    "count": 1,
    "option": ""},
"CROKER Re: Betrayed by Diego Audio Log": {"id": 283,
    "classification": "filler",
    "count": 1,
    "option": ""},
"CROKER Re: Cut off from pod 2 Audio Log": {"id": 284,
    "classification": "filler",
    "count": 1,
    "option": ""},
"CROKER Re: The resonator Audio Log": {"id": 285,
    "classification": "filler",
    "count": 1,
    "option": ""},
"BAYLISS Re: Wafer on Tau Ceti Audio Log": {"id": 286,
    "classification": "filler",
    "count": 1,
    "option": ""},
"KORENCHKIN Re: Rapture Audio Log": {"id": 287,
    "classification": "filler",
    "count": 1,
    "option": ""},
"BAYLISS Re: Tau Ceti, Pt. 2 Audio Log": {"id": 288,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Deck 7 Chemical Storage Manifest": {"id": 289,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Version 3 Modification Software Module": {"id": 290,
    "classification": "useful",
    "count": 2,
    "option": ""},
"POLITO Re: Pandora Audio Log": {"id": 291,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DIEGO Re: Last words Audio Log": {"id": 292,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Diego's Quarters Access Card": {"id": 293,
    "classification": "progression",
    "count": 1,
    "option": ""},
"Annelid Launcher": {"id": 294,
    "classification": "progression",
    "count": 3,
    "option": ""},
"6 Worm Clusters": {"id": 295,
    "classification": "useful",
    "count": 1,
    "option": ""},
"12 Worm Clusters": {"id": 296,
    "classification": "useful",
    "count": 2,
    "option": ""},
"PREFONTAINE Re: --- Audio Log": {"id": 297,
    "classification": "filler",
    "count": 1,
    "option": ""},
"73 Nanites": {"id": 298,
    "classification": "filler",
    "count": 2,
    "option": ""},
"PREFONTAINE Re: Stuck in here Audio Log": {"id": 299,
    "classification": "filler",
    "count": 1,
    "option": ""},
"PREFONTAINE Re: Opening the sphincter Audio Log": {"id": 300,
    "classification": "filler",
    "count": 1,
    "option": ""},
"PREFONTAINE Re: Central Control? Audio Log": {"id": 301,
    "classification": "filler",
    "count": 1,
    "option": ""},
"PREFONTAINE Re: Grinding noise Audio Log": {"id": 302,
    "classification": "filler",
    "count": 1,
    "option": ""},
"PREFONTAINE Re: Poor Claudette Audio Log": {"id": 303,
    "classification": "filler",
    "count": 1,
    "option": ""},
"PREFONTAINE Re: The many and us Audio Log": {"id": 304,
    "classification": "filler",
    "count": 1,
    "option": ""},
"PREFONTAINE Re: Annelid life cycle Audio Log": {"id": 305,
    "classification": "filler",
    "count": 1,
    "option": ""},
"PREFONTAINE Re: Many's Evolution Audio Log": {"id": 306,
    "classification": "filler",
    "count": 1,
    "option": ""},
"PREFONTAINE Re: The Many Audio Log": {"id": 307,
    "classification": "filler",
    "count": 1,
    "option": ""},
"37 Prisms": {"id": 308,
    "classification": "useful",
    "count": 1,
    "option": ""},
"Rickenbacker Chemical Storage Manifest": {"id": 309,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DELACROIX Re: Some small assistance Audio Log": {"id": 310,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DELACROIX Re: Stakes Audio Log": {"id": 311,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DELACROIX Re: The End Audio Log": {"id": 312,
    "classification": "filler",
    "count": 1,
    "option": ""},
"DELACROIX Re: A caution Audio Log": {"id": 313,
    "classification": "filler",
    "count": 1,
    "option": ""},
"Strong Metabolism OSUpgrade": {"id": 314,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Pharmo-Friendly OSUpgrade": {"id": 315,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Pack-Rat OSUpgrade": {"id": 316,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Speedy OSUpgrade": {"id": 317,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Sharpshooter OSUpgrade": {"id": 318,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Naturally Able OSUpgrade": {"id": 319,
    "classification": "progression",
    "count": 1,
    "option": "OSUpgrades"},
"Cybernetically Enhanced OSUpgrade": {"id": 320,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Tank OSUpgrade": {"id": 321,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Lethal Weapon OSUpgrade": {"id": 322,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Security Expert OSUpgrade": {"id": 323,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Smasher OSUpgrade": {"id": 324,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"CyberAssimilation OSUpgrade": {"id": 325,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Replicator Expert OSUpgrade": {"id": 326,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Power Psi OSUpgrade": {"id": 327,
    "classification": "trap",
    "count": 1,
    "option": "OSUpgrades"},
"Tinker OSUpgrade": {"id": 328,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Spatially Aware OSUpgrade": {"id": 329,
    "classification": "useful",
    "count": 1,
    "option": "OSUpgrades"},
"Strength Upgrade": {"id": 330,
    "classification": "progression",
    "count": 7,
    "option": "StatsSkillsPsi"},
"Endurance Upgrade": {"id": 331,
    "classification": "useful",
    "count": 7,
    "option": "StatsSkillsPsi"},
"Psi Upgrade": {"id": 332,
    "classification": "progression",
    "count": 7,
    "option": "StatsSkillsPsi"},
"Agility Upgrade": {"id": 333,
    "classification": "progression",
    "count": 7,
    "option": "StatsSkillsPsi"},
"Cybernetic Affinity Upgrade": {"id": 334,
    "classification": "progression",
    "count": 7,
    "option": "StatsSkillsPsi"},
"Hacking Upgrade": {"id": 335,
    "classification": "progression",
    "count": 8,
    "option": "StatsSkillsPsi"},
"Repair Upgrade": {"id": 336,
    "classification": "progression",
    "count": 8,
    "option": "StatsSkillsPsi"},
"Modify Upgrade": {"id": 337,
    "classification": "useful",
    "count": 8,
    "option": "StatsSkillsPsi"},
"Maintenance Upgrade": {"id": 338,
    "classification": "useful",
    "count": 8,
    "option": "StatsSkillsPsi"},
"Research Upgrade": {"id": 339,
    "classification": "progression",
    "count": 8,
    "option": "StatsSkillsPsi"},
"Conventional weapon Upgrade": {"id": 340,
    "classification": "progression",
    "count": 8,
    "option": "StatsSkillsPsi"},
"Energy weapon Upgrade": {"id": 341,
    "classification": "progression",
    "count": 8,
    "option": "StatsSkillsPsi"},
"Heavy weapon Upgrade": {"id": 342,
    "classification": "progression",
    "count": 8,
    "option": "StatsSkillsPsi"},
"Annelid weapon Upgrade": {"id": 343,
    "classification": "progression",
    "count": 8,
    "option": "StatsSkillsPsi"},
"First Tier Neural Capacity Psi Ability": {"id": 344,
    "classification": "progression",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Psycho-Reflective Screen Psi Ability": {"id": 345,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Neuro-Reflex Dampening Psi Ability": {"id": 346,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Kinetic Redirection Psi Ability": {"id": 347,
    "classification": "filler",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Pyschogenic Agility Psi Ability": {"id": 348,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Psychogenic Cyber-Affinity Psi Ability": {"id": 349,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Projected Cryokinesis Psi Ability": {"id": 350,
    "classification": "progression",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Remote Electron Tampering Psi Ability": {"id": 351,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Second Tier Neural Capacity Psi Ability": {"id": 352,
    "classification": "progression",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Anti-Entropic Field Psi Ability": {"id": 353,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Adrenaline Overproduction Psi Ability": {"id": 354,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Neural Decontamination Psi Ability": {"id": 355,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Cerebro-Stimulated Regeneration Psi Ability": {"id": 356,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Psychogenic Strength Psi Ability": {"id": 357,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Recursive Psionic Amplification Psi Ability": {"id": 358,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Localized Pyrokinesis Psi Ability": {"id": 359,
    "classification": "progression",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Third Tier Neural Capacity Psi Ability": {"id": 360,
    "classification": "progression",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Molecular Duplication Psi Ability": {"id": 361,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Electron Cascade Psi Ability": {"id": 362,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Energy Reflection Psi Ability": {"id": 363,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Neural Toxin-Blocker Psi Ability": {"id": 364,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Enhanced Motion Sensitivity Psi Ability": {"id": 365,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Projected Pyrokinesis Psi Ability": {"id": 366,
    "classification": "progression",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Psionic Hypnogenesis Psi Ability": {"id": 367,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Fourth Tier Neural Capacity Psi Ability": {"id": 368,
    "classification": "progression",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Photonic Redirection Psi Ability": {"id": 369,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Remote Pattern Detection Psi Ability": {"id": 370,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Electron Suppression Psi Ability": {"id": 371,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Psychogenic Endurance Psi Ability": {"id": 372,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Molecular Transmutation Psi Ability": {"id": 373,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Remote Circuitry Manipulation Psi Ability": {"id": 374,
    "classification": "progression",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Cerebro-Energetic Extension Psi Ability": {"id": 375,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Fifth Tier Neural Capacity Psi Ability": {"id": 376,
    "classification": "progression",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Advanced Cerebro-Stimulated Regeneration Psi Ability": {"id": 377,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Soma Transference Psi Ability": {"id": 378,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Instantaneous Quantum Relocation Psi Ability": {"id": 379,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Imposed Neural Restructuring Psi Ability": {"id": 380,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Metacreative Barrier Psi Ability": {"id": 381,
    "classification": "progression",
    "count": 1,
    "option": "StatsSkillsPsi"},
"External Psionic Detonation Psi Ability": {"id": 382,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"Psycho-Reflective Aura Psi Ability": {"id": 383,
    "classification": "useful",
    "count": 1,
    "option": "StatsSkillsPsi"},
"13 Cyber Modules": {"id": 384,
    "classification": "progression",
    "count": 2,
    "option": ""},
"14 Cyber Modules": {"id": 385,
    "classification": "progression",
    "count": 2,
    "option": ""},
"15 Cyber Modules": {"id": 386,
    "classification": "progression",
    "count": 4,
    "option": ""},
"25 Cyber Modules": {"id": 387,
    "classification": "progression",
    "count": 1,
    "option": ""},
"20 Cyber Modules": {"id": 388,
    "classification": "progression",
    "count": 9,
    "option": ""},
"30 Cyber Modules": {"id": 389,
    "classification": "progression",
    "count": 3,
    "option": ""},
"16 Cyber Modules": {"id": 390,
    "classification": "progression",
    "count": 1,
    "option": ""},
}