from typing import Dict, TypedDict
from BaseClasses import Item, ItemClassification

class SS2item(Item):
    game = "System Shock 2"

class ItemDict(TypedDict):
    id: int
    classification: ItemClassification
    count: int
    option: str


SS2items: Dict[str, ItemDict] = {
    "Wrench": {"id": 1,
        "classification": "filler",
        "count": 4,
        "option": ""},
    "Starting Wrench": {"id": 8,
        "classification": "filler",
        "count": 1,
        "option": "StartingWrench"},
    "Pistol": {"id": 9,
        "classification": "progression",
        "count": 2,
        "option": ""},
    "Damaged Shotgun": {"id": 10,
        "classification": "progression",
        "count": 6,
        "option": ""},
    "Broken Pistol": {"id": 11,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "Damaged Pistol": {"id": 12,
        "classification": "progression",
        "count": 13,
        "option": ""},
    "Psi Amp": {"id": 13,
        "classification": "progression",
        "count": 4,
        "option": ""},
    "Anti-radiation Hypo": {"id": 14,
        "classification": "progression",
        "count": 14,
        "option": ""},
    "MFD Game Player": {"id": 15,
        "classification": "filler",
        "count": 3,
        "option": ""},
    "Game Cartridge: Swinekeeper": {"id": 16,
        "classification": "filler",
        "count": 2,
        "option": ""},
    "10 Nanites": {"id": 17,
        "classification": "filler",
        "count": 21,
        "option": ""},
    "Hybrid Organ": {"id": 18,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "Small Standard Clip": {"id": 19,
        "classification": "useful",
        "count": 23,
        "option": ""},
    "Speed Booster": {"id": 20,
        "classification": "useful",
        "count": 7,
        "option": ""},
    "Standard Clip": {"id": 21,
        "classification": "useful",
        "count": 4,
        "option": ""},
    "Small AP Clip": {"id": 22,
        "classification": "useful",
        "count": 12,
        "option": ""},
    "DIEGO re: Yanking my chain Audio Log": {"id": 23,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Anti-Personnel Shotgun Shells": {"id": 24,
        "classification": "useful",
        "count": 7,
        "option": ""},
    "Medical Hypo": {"id": 25,
        "classification": "useful",
        "count": 25,
        "option": ""},
    "20 Nanites": {"id": 26,
        "classification": "filler",
        "count": 36,
        "option": ""},
    "CURTIS re: Coolant leaks Audio Log": {"id": 27,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Psi Hypo": {"id": 28,
        "classification": "progression",
        "count": 13,
        "option": ""},
    "GRASSI re: All work, no play Audio Log": {"id": 29,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Research Soft V1": {"id": 30,
        "classification": "filler",
        "count": 4,
        "option": ""},
    "DELACROIX re: Xerces Audio Log": {"id": 31,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "GRASSI re: Implant job Audio Log": {"id": 32,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "6 Rifled Slugs": {"id": 33,
        "classification": "useful",
        "count": 11,
        "option": ""},
    "4 Cyber Modules": {"id": 34,
        "classification": "progression",
        "count": 2,
        "option": ""},
    "5 Nanites": {"id": 35,
        "classification": "filler",
        "count": 18,
        "option": ""},
    "BrawnBoost": {"id": 36,
        "classification": "useful",
        "count": 3,
        "option": ""},
    "2 Cyber Modules": {"id": 37,
        "classification": "progression",
        "count": 14,
        "option": ""},
    "GRASSI re: Animal Rights? Audio Log": {"id": 38,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Anti-toxin hypo": {"id": 39,
        "classification": "useful",
        "count": 7,
        "option": ""},
    "WATTS re: Watson autopsy Audio Log": {"id": 40,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "WATTS re: Maintenance conduit Audio Log": {"id": 41,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "DELACROIX re: Not ready Audio Log": {"id": 42,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "CURTIZ re: More trouble": {"id": 43,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Strength Booster": {"id": 44,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "Deck 2 Chemical Storage Manifest": {"id": 45,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Fermium": {"id": 46,
        "classification": "useful",
        "count": 3,
        "option": ""},
    "Vanadium": {"id": 47,
        "classification": "progression",
        "count": 3,
        "option": ""},
    "Gallium": {"id": 48,
        "classification": "useful",
        "count": 3,
        "option": ""},
    "Antimony": {"id": 49,
        "classification": "progression",
        "count": 7,
        "option": ""},
    "Yttrium": {"id": 50,
        "classification": "progression",
        "count": 4,
        "option": ""},
    "Copper": {"id": 51,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "Californium": {"id": 52,
        "classification": "filler",
        "count": 4,
        "option": ""},
    "Sodium": {"id": 53,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "Osmium": {"id": 54,
        "classification": "useful",
        "count": 2,
        "option": ""},
    "Iridium": {"id": 55,
        "classification": "useful",
        "count": 6,
        "option": ""},
    "Arsenic": {"id": 56,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Cesium": {"id": 57,
        "classification": "useful",
        "count": 3,
        "option": ""},
    "Hassium": {"id": 58,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "Tellurium": {"id": 59,
        "classification": "progression",
        "count": 5,
        "option": ""},
    "Molybdenum": {"id": 60,
        "classification": "progression",
        "count": 0,
        "option": ""},
    "Technetium": {"id": 61,
        "classification": "progression",
        "count": 4,
        "option": ""},
    "Radium": {"id": 62,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "Barium": {"id": 63,
        "classification": "useful",
        "count": 4,
        "option": ""},
    "Selenium": {"id": 64,
        "classification": "progression",
        "count": 0,
        "option": ""},
    "Dead Power Cell": {"id": 65,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "Science access card": {"id": 66,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "Broken Grenade Launcher": {"id": 67,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "Damaged Assault Rifle": {"id": 68,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "Damaged Stasis Field Generator": {"id": 69,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "EMP Rifle": {"id": 70,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "KORENCHKIN re: First contact Audio Log": {"id": 71,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "TURNBULL re: Procedures Audio Log": {"id": 72,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "POLITO re: Strange AI Audio Log": {"id": 73,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "SUAREZ re:100% Torture Audio Log": {"id": 74,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "3 Proximity Grenades": {"id": 75,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "Auto-Diagnostic Medical Kit": {"id": 76,
        "classification": "useful",
        "count": 7,
        "option": ""},
    "Suit of Light Combat Armor": {"id": 77,
        "classification": "useful",
        "count": 5,
        "option": ""},
    "3 Fragmentation Grenades": {"id": 78,
        "classification": "useful",
        "count": 4,
        "option": ""},
    "Portable Battery": {"id": 79,
        "classification": "useful",
        "count": 2,
        "option": ""},
    "Box of 12 Anti-Personnel Bullets": {"id": 80,
        "classification": "useful",
        "count": 2,
        "option": ""},
    "Suit of Standard-Issue Combat Armor": {"id": 81,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "R & D access card": {"id": 82,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "Surgical Unit Activation Key": {"id": 83,
        "classification": "useful",
        "count": 3,
        "option": ""},
    "WATTS re: Nonsense Audio Log": {"id": 84,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "CURTIZ re: Lifts are out Audio Log": {"id": 85,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "CURTIZ re: Rad Hypos Audio Log": {"id": 86,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "WATTS re: Patient Watson Audio Log": {"id": 87,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "GRASSI re: Damn chimps Audio Log": {"id": 88,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "WATTS re: Patient Watson, pt. 2 Audio Log": {"id": 89,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "30 Nanites": {"id": 90,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Deck 2 crew access card": {"id": 91,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "Small Beaker": {"id": 92,
        "classification": "useful",
        "count": 3,
        "option": ""},
    "Broken Assault Rifle": {"id": 93,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "Laser Rapier": {"id": 94,
        "classification": "progression",
        "count": 2,
        "option": ""},
    "Psi Booster": {"id": 95,
        "classification": "useful",
        "count": 2,
        "option": ""},
    "Broken Shotgun": {"id": 96,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "MARTIN re: Ambush Audio Log": {"id": 97,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "DELACROIX re: A new friend? Audio Log": {"id": 98,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "CURTIZ re: Just us Audio Log": {"id": 99,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "SANGER re: Delacroix Audio Log": {"id": 100,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "PsiBoost(TM) Implant": {"id": 101,
        "classification": "useful",
        "count": 2,
        "option": ""},
    "Box of 6 Anti-personnel Bullets": {"id": 102,
        "classification": "useful",
        "count": 4,
        "option": ""},
    "Deck 1 Chemical Storage Manifest": {"id": 103,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Repair Soft V1": {"id": 104,
        "classification": "useful",
        "count": 3,
        "option": ""},
    "SANGER re: The soldiers Audio Log": {"id": 105,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "DELACROIX re: Tau Ceti 5": {"id": 106,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Hazard Suit": {"id": 107,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "DELACROIX re: Taking action Audio Log": {"id": 108,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "AP Clip": {"id": 109,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "CURTIZ re: That leak again Audio Log": {"id": 110,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "SANGER re: Locking Eng. Control": {"id": 111,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "DELACROIX re: Fluidics backdoor Audio Log": {"id": 112,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "MARTIN re: Cargo bay 2 Audio Log": {"id": 113,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "BRONSON re: Turret problems Audio Log": {"id": 114,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Annelid Healing Gland": {"id": 115,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "Security access card": {"id": 116,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "45m/dEx circuit board": {"id": 117,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "Broken Laser Pistol": {"id": 118,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "French-Epstein Device": {"id": 119,
        "classification": "useful",
        "count": 2,
        "option": ""},
    "SANGER re: Locked in Audio Log": {"id": 120,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "Cargo Bay 2A/2B access card": {"id": 121,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "SIDDONS re: Lame old me Audio Log": {"id": 122,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Game Cartridge: OverWorld Zero": {"id": 123,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "DIEGO re: Resist the call Audio Log": {"id": 124,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "SUAREZ re: Hang tight Audio Log": {"id": 125,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "3 Cyber Modules": {"id": 126,
        "classification": "progression",
        "count": 7,
        "option": ""},
    "SwiftBoost(TM) Implant": {"id": 127,
        "classification": "useful",
        "count": 2,
        "option": ""},
    "MALONE re: Further experiments Audio Log": {"id": 128,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "MALONE re: Psionic chimps! Audio Log": {"id": 129,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Hacking Soft V1": {"id": 130,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "BRONSON re: Hacking Turrets Audio Log": {"id": 131,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "DIEGO re: Is it so bad? Audio Log": {"id": 132,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "DELACROIX re: Be Brave Audio Log": {"id": 133,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Grenade Launcher": {"id": 134,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "Laser Pistol": {"id": 135,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "3 EMP grenade rounds": {"id": 136,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "DELACROIX re: A ray of hope Audio Log": {"id": 137,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "DELACROIX re: Killing the worms Audio Log": {"id": 138,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Game Cartridge: Swine Hunter": {"id": 139,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Toxin-A": {"id": 140,
        "classification": "progression",
        "count": 4,
        "option": ""},
    "LabAssistant(TM) Implant": {"id": 141,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "KORENCHKIN re: Miracles Audio Log": {"id": 142,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "MILLER re: Our work here Audio Log": {"id": 143,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "40 Nanites": {"id": 144,
        "classification": "filler",
        "count": 3,
        "option": ""},
    "MILLER re: Wondrous toy Audio Log": {"id": 145,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Hydroponics B access card": {"id": 146,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "DELACROIX re: Making a change Audio Log": {"id": 147,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "KORENCHKIN re: A new purpose Audio Log": {"id": 148,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Hydroponics A access card": {"id": 149,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "Auto-Repair Unit": {"id": 150,
        "classification": "progression",
        "count": 1,
        "option": ""},
    "MILLER re: The children Audio Log": {"id": 151,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Maintenance Tool": {"id": 152,
        "classification": "useful",
        "count": 8,
        "option": ""},
    "LOESSER re: Where are they? Audio Log": {"id": 153,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "MILLER re: Nurse bloome Audio Log": {"id": 154,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Version 1 Modification Software Module": {"id": 155,
        "classification": "useful",
        "count": 1,
        "option": ""},
    "BLOOME re: Worried Audio Log": {"id": 156,
        "classification": "filler",
        "count": 1,
        "option": ""},
    "Deck 3 Chemical Storage Manifest": {"id": 157,
        "classification": "filler",
        "count": 1,
        "option": ""},
}