from typing import Dict, TypedDict
from BaseClasses import Location

class SS2location(Location):
    game = "System Shock 2"

class LocDict(TypedDict):
    id: int
    region: str
    option: str
    reqitems: dict #"name": intamount

SS2locations: Dict[str, LocDict] = {
"Directly After airlock medsci1, can't receive items until collected": {"id": 1, #replaces wrench behind airlock
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"In body at start of game medsci1": {"id": 8,
    "region": "medsci1",
    "option": "StartingWrench",
    "reqitems": {}},
"Next to body near Dr Watts in R&D medsci1": {"id": 9,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"In a body in R&D inside room medsci1": {"id": 10,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"Next to body in closet in R&D medsci1": {"id": 11,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"In body in chemical storeroom medsci1": {"id": 12,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In body in xerxes circular room medsci1": {"id": 13,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In body after airlock upper floor medsci1": {"id": 14,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"above on ledge behind help desk near medical entrance medsci1": {"id": 15,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In body near medical entrance medsci1": {"id": 16,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In body near medical entrance 2 medsci1": {"id": 17,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"On desk near medical entrance medsci1": {"id": 18,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"Near battery recharger and turrets medsci1": {"id": 19,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In Pipe Hybrid in xerxes circular room medsci1": {"id": 20,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"Directly after airlock to the left above on beam medsci1": {"id": 21,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"Directly after airlock to the left above on beam 2 medsci1": {"id": 22,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"In body directly after airlock to the left medsci1": {"id": 23,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"In body in corridor in R&D medsci1": {"id": 24,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"In body in corridor in R&D 2 medsci1": {"id": 25,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"On counter near sink in R&D medsci1": {"id": 26,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"Next to pipes in corridor in R&D medsci1": {"id": 27,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"In body near Dr Watts in R&D medsci1": {"id": 28,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"On counter near sink in R&D 2 medsci1": {"id": 29,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"In container in R&D medsci1": {"id": 30,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"In container in R&D 2 medsci1": {"id": 31,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"Behind turret near crew quarters entrance medsci1": {"id": 32,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"Under pipe near turret near crew quarters entrance medsci1": {"id": 33,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In body near sink in R&D medsci1": {"id": 34,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"On ground near Dr Watts in R&D medsci1": {"id": 35,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"Container directly after airlock medsci1": {"id": 36,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"Between beams in circular xerxes room medsci1": {"id": 37,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"On desk near medical entrance 2 medsci1": {"id": 38,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In body bags near Quantum Bio-Reconstruction Machine medsci1": {"id": 39,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In body bags near Quantum Bio-Reconstruction Machine 2 medsci1": {"id": 40,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"On ground near body bags near Quantum Bio-Reconstruction Machine medsci1": {"id": 41,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In body next to engineering ladder medsci1": {"id": 42,
    "region": "medsci1",
    "option": "",
    "reqitems": {"WATTS re: Maintenance conduit Audio Log": 1, "Science access card": 1}},
"On ground next to I can't find my keycard ghost in area after airlock medsci1": {"id": 43,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"In body in hallway toward R&D medsci1": {"id": 44,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"Body bag in hallway near R&D medsci1": {"id": 45,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In security crate in surveillance room that the first enemy runs out of medsci1": {"id": 46,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1, "Science access card": 1}},
"In security crate in surveillance room that the first enemy runs out of 2 medsci1": {"id": 47,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1, "Science access card": 1}},
"In containers in closet of the surveillance room that the first enemy runs out of medsci1": {"id": 48,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"On top of container near hackable closet in after airlock area medsci1": {"id": 49,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"Behind Glass in area after airlock medsci1": {"id": 50,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"Behind Glass in area after airlock 2 medsci1": {"id": 51,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"In body in lower central area after airlock medsci1": {"id": 52,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"In body near glass in area after airlock medsci1": {"id": 53,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"In body near hackable closet in area after airlock medsci1": {"id": 54,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"In container near hackable closet in area after airlock medsci1": {"id": 55,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"Near pipe in room with glass in area after airlock medsci1": {"id": 56,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"In hackable closet in area after airlock medsci1": {"id": 57,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Hacking Upgrade": 1}},
"In hackable closet in area after airlock 2 medsci1": {"id": 58,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Hacking Upgrade": 1}},
"In hackable closet in area after airlock 3 medsci1": {"id": 59,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Hacking Upgrade": 1}},
"In body near charger near chem storage room medsci1": {"id": 60,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In containers in room in hallway where someone runs towards R&D medsci1": {"id": 61,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In containers in room in hallway where someone runs towards R&D medsci1 2": {"id": 62,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In containers in room in hallway where someone runs towards R&D medsci1 3": {"id": 63,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In containers in room in hallway where someone runs towards R&D medsci1 4": {"id": 64,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In security crate in room in hallway where someone runs towards R&D medsci1": {"id": 65,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1, "Science access card": 1}},
"In security crate in room in hallway where someone runs towards R&D 2 medsci1": {"id": 66,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1, "Science access card": 1}},
"In security crate in room in hallway where someone runs towards R&D 3 medsci1": {"id": 67,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1, "Science access card": 1}},
"In trashcan in lower area with explosives directly outside R&D medsci1": {"id": 68,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In security crate in lower area with explosives directly outside R&D medsci1": {"id": 69,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In security crate in lower area with explosives directly outside R&D 2 medsci1": {"id": 70,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In Dr Watts in R&D medsci1": {"id": 71,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"In Dr Watts in R&D 2 medsci1": {"id": 72,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"On operating table near entrance to R&D medsci1": {"id": 73,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"On stacked boxes in charger room medsci1": {"id": 74,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In body near charger near chem storage room 2 medsci1": {"id": 75,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"Under vent in corner of room near R&D entrance medsci1": {"id": 76,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In body near chem storage room medsci1": {"id": 77,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"On bench in xerxes circular room medsci1": {"id": 78,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In containers in chem storage room medsci1": {"id": 79,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"Above on pipe near turret near crew quarters entrance medsci1": {"id": 80,
    "region": "medsci1",
    "option": "",
    "reqitems": {"outofreach": "blast, agi, wall, orb, pull", "Science access card": 1}},
"Above on pipe near turret near crew quarters entrance 2 medsci1": {"id": 81,
    "region": "medsci1",
    "option": "",
    "reqitems": {"outofreach": "blast, agi, wall, orb, pull", "Science access card": 1}},
"On ground in chemical storeroom medsci1": {"id": 82,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves medsci1": {"id": 83,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 2 medsci1": {"id": 84,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 3 medsci1": {"id": 85,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 4 medsci1": {"id": 86,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 5 medsci1": {"id": 87,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 6 medsci1": {"id": 88,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 7 medsci1": {"id": 89,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 8 medsci1": {"id": 90,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 9 medsci1": {"id": 91,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 10 medsci1": {"id": 92,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 11 medsci1": {"id": 93,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 12 medsci1": {"id": 94,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 13 medsci1": {"id": 95,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 14 medsci1": {"id": 96,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 15 medsci1": {"id": 97,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"In chemical storeroom on/near shelves 16 medsci1": {"id": 98,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"On ground near body near medical entrance medsci1": {"id": 99,
    "region": "medsci1",
    "option": "",
    "reqitems": {"Science access card": 1}},
"On ground near glass in area after airlock medsci1": {"id": 100,
    "region": "medsci1",
    "option": "",
    "reqitems": {}},
"In body in closet in R&D medsci1": {"id": 101,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"In body in closet in R&D 2 medsci1": {"id": 102,
    "region": "medsci1",
    "option": "",
    "reqitems": {"R & D access card": 1, "Science access card": 1}},
"Under counter in snack room with replicator medsci2crew": {"id": 103,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"On ground in armory near entrance medsci2crew": {"id": 104,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"BRONSON re: MedSci armory code Audio Log": 1}},
"On bench in armory near entrance medsci2crew": {"id": 105,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"BRONSON re: MedSci armory code Audio Log": 1}},
"On bench in armory near entrance 2 medsci2crew": {"id": 106,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"BRONSON re: MedSci armory code Audio Log": 1}},
"In desk in flooded room closest to entrance medsci2crew": {"id": 107,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"On high ledge near camera in flooded hallway medsci2crew": {"id": 108,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"On ground near body in maintenance alcove above room accross from Watts room in flooded area medsci2crew": {"id": 109,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"In wall cutout in closet in room next to med entrance medsci2crew": {"id": 110,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"In desk in closet in room next to med entrance medsci2crew": {"id": 111,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"In desk in room opposite snack room medsci2crew": {"id": 112,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"On metal desk near armory medsci2crew": {"id": 113,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"In desk in flooded room underneath camera medsci2crew": {"id": 114,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"On desk in flooded room underneath camera medsci2crew": {"id": 115,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"In body in flooded room with broken door in front medsci2crew": {"id": 116,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"On ledge in maintenance alcove above room accross from Watts room in flooded area medsci2crew": {"id": 117,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"In body in maintenance alcove above room accross from Watts room in flooded area medsci2crew": {"id": 118,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"On pipe above Watts room in flooded hallway medsci2crew": {"id": 119,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"outofreach": "blast, wall, pull"}},
"In desk in Watts room medsci2crew": {"id": 120,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"On bench in flooded room closest to entrance medsci2crew": {"id": 121,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"In body in flooded hallway near ramp medsci2crew": {"id": 122,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"In waste barrel in flooded bathroom medsci2crew": {"id": 123,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"In security crate in room with forcefield in walkway above flooded hallway medsci2crew": {"id": 124,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1}},
"In desk in room with forcefield in walkway above flooded hallway medsci2crew": {"id": 125,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"Behind forcefield in wall cutout in room in walkway above flooded hallway medsci2crew": {"id": 126,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"Hacking Upgrade": 1, "Repair Upgrade": 1}},
"Behind forcefield in wall cutout in room in walkway above flooded hallway 2 medsci2crew": {"id": 127,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"Hacking Upgrade": 1, "Repair Upgrade": 1}},
"In body in armory near entrance medsci2crew": {"id": 128,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"BRONSON re: MedSci armory code Audio Log": 1}},
"In crates in armory near entrance medsci2crew": {"id": 129,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"BRONSON re: MedSci armory code Audio Log": 1}},
"In crates in armory near entrance 2 medsci2crew": {"id": 130,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"BRONSON re: MedSci armory code Audio Log": 1}},
"In crates in armory near entrance 3 medsci2crew": {"id": 131,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"BRONSON re: MedSci armory code Audio Log": 1}},
"In crates in armory near entrance 4 medsci2crew": {"id": 132,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"BRONSON re: MedSci armory code Audio Log": 1}},
"In crates in armory near entrance 5 medsci2crew": {"id": 133,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"BRONSON re: MedSci armory code Audio Log": 1}},
"On ground in armory near entrance 2 medsci2crew": {"id": 134,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {"BRONSON re: MedSci armory code Audio Log": 1}},
"In desk in Watts room 2 medsci2crew": {"id": 135,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"On wall across from lounge near entrance medsci2crew": {"id": 136,
    "region": "medsci2crew",
    "option": "OSUpgrades",
    "reqitems": {}},
"On wall across from lounge near entrance 2 medsci2crew": {"id": 137,
    "region": "medsci2crew",
    "option": "OSUpgrades",
    "reqitems": {}},
"On wall across from lounge near entrance 3 medsci2crew": {"id": 138,
    "region": "medsci2crew",
    "option": "OSUpgrades",
    "reqitems": {}},
"On wall across from lounge near entrance 4 medsci2crew": {"id": 139,
    "region": "medsci2crew",
    "option": "OSUpgrades",
    "reqitems": {}},
"Behind replicator above lounge medsci2crew": {"id": 140,
    "region": "medsci2crew",
    "option": "",
    "reqitems": {}},
"In body in recovery room with monkeys on lower floor medsci2med": {"id": 141,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In security crate on top level in 3 level room near biopsy sign medsci2med": {"id": 142,
    "region": "medsci2med",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1}},
"In body in room with shelves and security crate near camera medsci2med": {"id": 143,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In security crate in room with shelves and security crate near camera medsci2med": {"id": 144,
    "region": "medsci2med",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1}},
"On desk in recovery upper level medsci2med": {"id": 145,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In desk in recovery upper level medsci2med": {"id": 146,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In desk in recovery upper level 2 medsci2med": {"id": 147,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"On ledge accross from recovery upper level medsci2med": {"id": 148,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"On desk in recovery lower level medsci2med": {"id": 149,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In body in recovery room with monkeys on lower floor 2 medsci2med": {"id": 150,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In desk in room with resurrection station medsci2med": {"id": 151,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In desk in recovery lower level medsci2med": {"id": 152,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In crates in recovery lower area medsci2med": {"id": 153,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In crates in recovery lower area 2 medsci2med": {"id": 154,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In crates or corpse in radiated area with radiation barrel medsci2med": {"id": 155,
    "region": "medsci2med",
    "option": "",
    "reqitems": {"Anti-radiation Hypo": 2}},
"In crates or corpse in radiated area with radiation barrel 2 medsci2med": {"id": 156,
    "region": "medsci2med",
    "option": "",
    "reqitems": {"Anti-radiation Hypo": 2}},
"In crates or corpse in radiated area with radiation barrel 3 medsci2med": {"id": 157,
    "region": "medsci2med",
    "option": "",
    "reqitems": {"Anti-radiation Hypo": 2}},
"On counter near sink in radiated area with radiation barrel medsci2med": {"id": 158,
    "region": "medsci2med",
    "option": "",
    "reqitems": {"Anti-radiation Hypo": 2}},
"On counter near sink in radiated area with radiation barrel 2 medsci2med": {"id": 159,
    "region": "medsci2med",
    "option": "",
    "reqitems": {"Anti-radiation Hypo": 2}},
"In desk in radiated icu area medsci2med": {"id": 160,
    "region": "medsci2med",
    "option": "",
    "reqitems": {"Anti-radiation Hypo": 2}},
"In security crate in radiated icu area medsci2med": {"id": 161,
    "region": "medsci2med",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1, "Anti-radiation Hypo": 2}},
"In security crate in radiated icu area 2 medsci2med": {"id": 162,
    "region": "medsci2med",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1, "Anti-radiation Hypo": 2}},
"In security crate in radiated icu area 3 medsci2med": {"id": 163,
    "region": "medsci2med",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1, "Anti-radiation Hypo": 2}},
"In desk near 3 level room near biopsy sign medsci2med": {"id": 164,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In body in closet near bloody RUN sign and radiated room with radiation barrels medsci2med": {"id": 165,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"On shelf in closet near bloody RUN sign and radiated room with radiation barrels medsci2med": {"id": 166,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"On counter on bottom level in 3 level room near biopsy sign medsci2med": {"id": 167,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"On counter on bottom level in 3 level room near biopsy sign 2 medsci2med": {"id": 168,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In crates on top level in 3 level room near biopsy sign medsci2med": {"id": 169,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In crates on top level in 3 level room near biopsy sign 2 medsci2med": {"id": 170,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In security crate on top level in 3 level room near biopsy sign 2 medsci2med": {"id": 171,
    "region": "medsci2med",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1}},
"In body or crate in closet near biopsy sign medsci2med": {"id": 172,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In body or crate in closet near biopsy sign 2 medsci2med": {"id": 173,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In body or crate in closet near biopsy sign 3 medsci2med": {"id": 174,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"In body on bottom level in 3 level room near biopsy sign 2 medsci2med": {"id": 175,
    "region": "medsci2med",
    "option": "",
    "reqitems": {}},
"Out of view above on pipe near closet near biopsy sign medsci2med": {"id": 176,
    "region": "eng1",
    "option": "",
    "reqitems": {"outofreach": "wall"}},
"In tunnel in port nacelle near engine core eng1": {"id": 177,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In body in recessed area behind engine core eng1": {"id": 178,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In tunnel in stbd nacelle near engine core eng1": {"id": 179,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In crate in tunnel in stbd nacelle near engine core eng1": {"id": 180,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In crate in tunnel in stbd nacelle near engine core 2 eng1": {"id": 181,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In crate in tunnel in stbd nacelle near engine core 3 eng1": {"id": 182,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"On ground near body in stbd nacelle near outer back of tunnel eng1": {"id": 183,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"On ground near body in lower walkway eng1": {"id": 184,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"On ground near body crushed by pipe in open room with keypad eng1": {"id": 185,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In crates or body crushed by pipe in open room with keypad eng1": {"id": 186,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In crates or body crushed by pipe in open room with keypad 2 eng1": {"id": 187,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On ground near body in radiated hallways along shuttle bay arrows eng1": {"id": 188,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On ground near body in radiated hallways near aux storage eng1": {"id": 189,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On ground near bodies on stairs that lead to cargo bay eng1": {"id": 190,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On ground near body near engineering control grav shafts eng1": {"id": 191,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On ground near bodies in room after engineering control grav shafts eng1": {"id": 192,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On ground outside fluidics controls room near engineering control gravshafts eng1": {"id": 193,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body in control room in port nacelle near engine core eng1": {"id": 194,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In body in recessed area behind engine core 2 eng1": {"id": 195,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"On ground near grate to the right of the engine core eng1": {"id": 196,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In body in control room in stbd nacelle near engine core eng1": {"id": 197,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"On desk in control room in stbd nacelle near engine core eng1": {"id": 198,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In body in stbd nacelle near outer back of tunnel eng1": {"id": 199,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"On shelf directly next to entrance eng1": {"id": 200,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In desk directly next to entrance eng1": {"id": 201,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In desk directly next to entrance 2 eng1": {"id": 202,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In desk directly next to entrance 3 eng1": {"id": 203,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In desk directly next to entrance 4 eng1": {"id": 204,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In enemy near body in radiated hallways along shuttle bay arrows eng1": {"id": 205,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body in radiated hallways along shuttle bay arrows eng1": {"id": 206,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On raised side of hallway in radiated hallways along shuttle bay arrows eng1": {"id": 207,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In other body in radiated hallways along shuttle bay arrows eng1": {"id": 208,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body in radiated hallways near aux storage eng1": {"id": 209,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On desk in office near engine core computer eng1": {"id": 210,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In desk in office near engine core computer eng1": {"id": 211,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In desk in office near engine core computer 2 eng1": {"id": 212,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In security crate in lower walkway next to elevator eng1": {"id": 213,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1, "Hacking Upgrade": 2, "Repair Upgrade": 1}},
"In security crate in lower walkway next to elevator 2 eng1": {"id": 214,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1, "Hacking Upgrade": 2, "Repair Upgrade": 1}},
"In body in radiated hallways along engine core arrows eng1": {"id": 215,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In enemies in lower walkway eng1": {"id": 216,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In security crate in radiated hallways along engine core signs eng1": {"id": 217,
    "region": "eng1",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1}},
"In security crate in radiated hallways along engine core signs 2 eng1": {"id": 218,
    "region": "eng1",
    "option": "",
    "reqitems": {"Hacking Upgrade": 2, "Repair Upgrade": 1}},
"In bodies in lower walkway eng1": {"id": 219,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In bodies in lower walkway 2 eng1": {"id": 220,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In bodies in lower walkway 3 eng1": {"id": 221,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In bodies in lower walkway 4 eng1": {"id": 222,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In bodies in lower walkway 5 eng1": {"id": 223,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In enemies in lower walkway 2 eng1": {"id": 224,
    "region": "eng1",
    "option": "",
    "reqitems": {"45m/dEx circuit board": 1, "SANGER re: Locked in Audio Log": 1}},
"In desk in room connected to chemical storage eng1": {"id": 225,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In desk in room connected to chemical storage 2 eng1": {"id": 226,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves eng1": {"id": 227,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 2 eng1": {"id": 228,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 3 eng1": {"id": 229,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 4 eng1": {"id": 230,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 5 eng1": {"id": 231,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 6 eng1": {"id": 232,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 7 eng1": {"id": 233,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 8 eng1": {"id": 234,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 9 eng1": {"id": 235,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 10 eng1": {"id": 236,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 11 eng1": {"id": 237,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 12 eng1": {"id": 238,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 13 eng1": {"id": 239,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 14 eng1": {"id": 240,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 15 eng1": {"id": 241,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 16 eng1": {"id": 242,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 17 eng1": {"id": 243,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In chemical storage room on shelves 18 eng1": {"id": 244,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
"In enemy in radiated hallways near chemical storage eng1": {"id": 245,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body outside chemical storage eng1": {"id": 246,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body outside chemical storage 2 eng1": {"id": 247,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On ground in radiated hallways near chemical storage eng1": {"id": 248,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body in radiated hallways somewhat near chemical storage eng1": {"id": 249,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On raised side of hallway in radiated hallways somewhat near chemical storage near shuttle bay arrow eng1": {"id": 250,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On ground in radiated hallway somewhat near chemical storage eng1": {"id": 251,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In crates in aux storage eng1": {"id": 252,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In crates in aux storage 2 eng1": {"id": 253,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In crates in aux storage 3 eng1": {"id": 254,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In crates in aux storage 4 eng1": {"id": 255,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In crates in aux storage 5 eng1": {"id": 256,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On ground in radiated hallways outside aux storage eng1": {"id": 257,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body in bottom of central room near elevator eng1": {"id": 258,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body in bottom of central room near elevator 2 eng1": {"id": 259,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On ground at top of central room near elevator eng1": {"id": 260,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On ground in room with elevator near door to ramp eng1": {"id": 261,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body in room with elevator eng1": {"id": 262,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In bodies in room after ramp near elevator eng1": {"id": 263,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"Above on ledge in room with xerxes face after ramp near elevator eng1": {"id": 264,
    "region": "eng1",
    "option": "",
    "reqitems": {"outofreach": "blast, wall, pull"}},
"Under grate in area above engineering control grav shaft eng1": {"id": 265,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body near engineering control grav shaft eng1": {"id": 266,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body near engineering control grav shaft 2 eng1": {"id": 267,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In bodies in room after engineering control grav shaft eng1": {"id": 268,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In bodies in room after engineering control grav shaft 2 eng1": {"id": 269,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In bodies in room after engineering control grav shaft 3 eng1": {"id": 270,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"On ground outside fluidics controls room near engineering control gravshafts 2 eng1": {"id": 271,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body in fluidics control room above engineering control grav shaft eng1": {"id": 272,
    "region": "eng1",
    "option": "",
    "reqitems": {"SANGER re: Locked in Audio Log": 1}},
"On ground in fluidics control room above engineering control grav shaft eng1": {"id": 273,
    "region": "eng1",
    "option": "",
    "reqitems": {"SANGER re: Locked in Audio Log": 1}},
"On ground in room with bodies after engineering control grav shaft eng1": {"id": 274,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body or lockers in security office after engineering control grav shaft eng1": {"id": 275,
    "region": "eng1",
    "option": "",
    "reqitems": {"Security access card": 1}},
"In body or lockers in security office after engineering control grav shaft 2 eng1": {"id": 276,
    "region": "eng1",
    "option": "",
    "reqitems": {"Security access card": 1}},
"In body or lockers in security office after engineering control grav shaft 3 eng1": {"id": 277,
    "region": "eng1",
    "option": "",
    "reqitems": {"Security access card": 1}},
"In body or lockers in security office after engineering control grav shaft 4 eng1": {"id": 278,
    "region": "eng1",
    "option": "",
    "reqitems": {"Security access card": 1}},
"In cutout in wall in security office after engineering control grav shaft eng1": {"id": 279,
    "region": "eng1",
    "option": "",
    "reqitems": {"Security access card": 1}},
"In body outside security office after engineering control grav shaft eng1": {"id": 280,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In body outside security office after engineering control grav shaft 2 eng1": {"id": 281,
    "region": "eng1",
    "option": "",
    "reqitems": {}},
"In chemical storage room on shelves 19 eng1": {"id": 282,
    "region": "eng1",
    "option": "",
    "reqitems": {"DELACROIX re: Fluidics backdoor Audio Log":1}},
}